---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inception-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgBVn9cFWIN4+ks9u791Mqoo/1KT0RZuci7b8DNGcW7UND9LVHUGZRzL6olr+V4ex72s3PpaKpTiXhxzADzwowmhd1IlC6dnaah45cnLY1rqEU9yaQJdkcbgi+c8LfI5BTbRly3OV3CUfbKxZxEkw30CqTzsCE4wmtqVFX7s04kYi2P/+fLHfmYt8UmRI1SIGmXWJJH/avwchkMDYbb1m4ANAdAtqKIuoXTnaCVpE4rAZlziuLDZRCu2Z3vqy+B/rp2vGmyI51NZlmmKIYdkyvvZQVKZPDByknnXQErfmiXpLCDt/TbesIbkneCdFSXYUKEFKi9+Pbx5A5pTxIWnDsUL/pldVb1aIk08pyHwjwgA5U3W6UCpvvdC50YHFfpLrZox2zk4JfmOoPUeYcOK3oGVVRr2lpT2Ba/97tfPsTdVxTPMZYAuucycmO5YSWhjemjMO/8Lqm9Y/aN9rmXWw5tsx3zSL01pmFFuYzLA+6Ib6klvPmF04RE85bKepd82xMpjXg9rkE1ojI4G/lsL/L/zkQ1LJCjHWKiqIXVdZdkEC9ppT8BBRSz2+N3DXKOhq+LbnvINkuOaArUXeEyRd85oynarxiGrN5raH23iBPc8nXStUlgZCIhiwF9LUtv4FHbrTFK6y7LPHUxs2L212n41uq2HwYkalbIMiqtgI86O3g8v2zEHxxRfPig5NMAb6xqp2BXWyaNqEWi7tm+zlXCj8ulGHqlaCYC7UhU7ltQgFKVdNw==
    slack-webhook-url: AgBuashUlJov+9y+HKEPRJzP50wusUqccMnFJx+TBm+t6kBLp2ZtjOddZGsn2Rmlwwjh41L+5sxpCsDJWMYYRNxlHXGR1fkDAWj9++0YtRGCcetGn947A8fft7vkTd3YZ+KqZFMCu8qjuVJGfHlCIlmY19xQxl2koiCe8Vtsjh6gqOgQ4Y82YMJBXt/J7DQxdHYLLEthbasaxtITJhdKaDkzf+07Q6SpolcJNVTHm1WBVjZ9HHNAGBBaecOJIGaT9KUmwHooGfpklntuWMjeNUojg9epgaZCvIMV3OZFF14NQEtw2fCOEaKAbLXUqOs5jblfy8r2W+BeCZoLXE6wvAyrn4kB7ieC8K0I6EnDX37SXk73V4metQl1mbZxJJmpwAIZ6A12o1acZ2zVz422lVF6Xpjx/jMTU5YWnaz6NDMaN+RtsAEUO116HxfNEmI9JD+GyvuuZaZGgS7XZC9mmkZIvkgksVlER5uMynYV5CN7v6ahWWxsBzOUhXpfEyM7bf0BnJ2JoLCKuH3wa42EgTHwx0sQiqyS/IOOZV84w9yjkXoQxexOKUR44L9o3D35DAOasteBFd0nNfNkEzZww1UzTAOJrn21udbcg/Hoa894VcUq5NP0ZQqImpIhx4EjhFsGXiLzd+C07Rm4g88sDcY25jm7FXGzAbNkojWOXIR8JK1JyGasoT8/hyLsFENuAdCrPG1qyCq3oUuEZyzNVlIxbSmfR/bq5KvIpvQUj8Q6HqAeyom6p05PtC5ktoV6WtTwK/zn7CUSS4SFbFAs27jVFnAJlMwi+L012sKKoja67c8=
  template:
    metadata:
      creationTimestamp: null
      name: inception-secret
      namespace: default
