---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inception-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgBXZ3kvzbCVs1X3FYQIE13WtwmTulziT6dr/i3kuEkdyP4lFS/r+obngBDbPh/EqxLxv5v3sQRuKRfQ570eq+rn4Gb5k63MVZNhcTYgkHtve01rj5xT6ZIM+JmMguPnDIpGFJSMkqrS13eQ7JWWoPS/NcQMYNZYyz58AydhxBgwj06zqdwOqv3vXu+k8vCoE/pW6A+kMZoLRYSEI1FIQ38H6NmReOCvaHIZ99tf+Nd21PPIMWuSdv6WoF8k3YRJMr0OC+vasoqhmW1fCNw7Y2a8NV2pfLWRMbSa68tMUaxPh4ePUOW7A7RwkPV9HmpbVGNkEYXSfjiw8e4Tv5BFWpgJV55M1w+7BAyH/sSQkplQLIdlTq4H02ASYIa27Z81u+NA2qm752UdQ/urn5SM5f8utfIODOJUQemn84+/7UVhk+3y42ShxWFGylFr0JhYXhsg+dyw4TZ5B4QaX27lck7sBQIVjLCyH3j+hDSnOJYpPrLCG7CQbW8WqzHs9pqEMd1i1ETcLJ3x8neoxHNw44xwuSqWRqJmw5lpFtYLGVn5dVs/qO0cyTOKyNTlf0xeLqGgDXj9w0N6G8qEleSc+D1MyXusF+bx4PtBPbGiz6+AUEnhC11p02kwCIkO7kM05SXtIq9wL6U5GtCshunUQ1FelILd2W99eSPcR8AQ1IUi+2SPFhh8xQqyLI1K5Dvikx/UDzQXCpiYE3VrZaCEDidr33lIHLScw8W81vbEp5qrkbPVdg==
    slack-webhook-url: AgBha6z5OPg0JWidz4rUjGGCE3xxZ0nwaIQSV4Kw7BTrE2Dhtet9Vt4x9oSd/Yp383RHAecdM0tZsSeCFHQYh3MOnFGSVMgwR1Bjm/9t7HwZ7sJLmdRRUxfsB3JR7uMoGQoBtFX+AbI1xLcabheFSVPBwbWkmHT9Z8MRal4KSeHjZQpiYwWgKfYpjz0ralhYyKwNR6ZrS7lqhjyEH/5P5iGNWMT3Ufcj82UyA9kKoNIk46LUMkUwZWXQ5dhW70Pfxcr38pBIRIUu8OnSYqUIt08nz0hgBf1MEypuOWIwuuLDgnTj2Iw4D3iMSLPtaJJK6W5vy9/hdz6K8uG9MixSb4jAwfXoZs6Oy8xXz317v/kEz0X//KvsS58TWt2/JHc+nRtrZaVoQeVLNj5oK20UDBOA5CEzqRH2YOz1VX+fXfI0RVewXmPXJNqXH+y1G6PQhhYdmqy9afW9h8krzB/NHIjIIbvyrZaB5XxviCa+CdNPta+pPCLxbF/Q8xzRG8RzJs6Jomxf38iMQ84MvCGckDYkIWX9uE7sRAKOmQKCR9xsjtXTPpN30uL/sQYmJycg1+0DIO/xuAqjhLgrzjTWRR2GSxqlgJ+6wQSsx5FQxlCqMbAMuw9nfX053HbufN1zGlDI9U+kr1m69iy+XAGRYBtyK5w4nYcpR+N4XNKAK7OIBWZom42U8IKHLL1eOA6ZHBHXS+mBhns6qvU2IvMMVzQVhHtDWn2hWX1wv53bRApt5s7BZ33Gwtpf6CYOF5esmmzPtpMGLJAxmcaRviMFoPxdFmLfQ20JZb5qPZ/C1yRu4jM=
  template:
    metadata:
      creationTimestamp: null
      name: inception-secret
      namespace: default
