---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: inception-secret
  namespace: default
spec:
  encryptedData:
    api-key: AgCDxAvLaogepHec2fYJJ9kwdYZr4gIezE+wiMiC/41C0tSq27ER5brRzdszqOiRrr0O8PcAUHROatcdMX29jdeCuEh7VxFBoo0dny+AaLkM3TnEYpeHUpOkr17i2ybxAog/9rt5/o2TycfF8dOXqOB5/YQRTZ/TDdxnegvDuc7qAa1j5GYCzwP+M9MV8RJi09hI80tyYrS8h+OYnUkcAgNqGbrj7jhFTWF+iYJ5HL3INyzDgNilQidYWSvAtAdYqdGC2aX0+/2GeXoCNbn3mOk04BQcp3C9OqGD+D/xgQjI8xBykT6G2pHEPgb1Mp5ombF3zQ67ZZLuh8HX+bhl9TK70GRodS2cUO2NmLMI74igJHOp5we5Ula4CorcFKwTucOtCK8jR547pEL2P/P6xsvXhVTjENj1/FeOHthbwK93vrxVcoPdicPmiiQejMPHhdlRqpLxLTUQAiRVYxWmph5Zv48ZLG4BgG3Zr3yb8+9NQuqXFiEArcGqiU6viGko3q9hXe3FwYiWbeLGzzmU6Si/U/SclnNE11aMKrDNbxbFOzwtAqS151BNkqfTwEZnQNfnieWwclfyoHitrOhIPUD0VfcLyMG7B8d6dkdvlpFDxlCv720HE536VLFU7hYkLkLkdhMLMuPkymFEfokOqF9ftSisMurz7uMQzPs6qaB2+xe50MhjGd+bPQSeN+kuLxns8CzlPgJdY6XOEmgQPUVC4Vh4JNVEreIJvIudw0jC1LvkZg==
    slack-webhook-url: AgCBeQ9TLGN+suZ1UwFG5Ry3DKQ4voXfM64pN9IUaHGvkAdDm04fAcDo1EiTrQv6HNx3PpkN+FGYUJk8LZjWJoEXMuFBEqSvDxKZjGTH0dbyTCaw+OcX6D7SG2zIVNX6QAkadcpBZevkFpHx45gTHAaHKgiIxyhIUJlmESZ/GB5aYtBN0FotjfLlgJAwA4ahQl0TTcvKF2h0qJziN3J0B2dYQbvzc10w+HS04LX+C7+fcJvk7zFc8jgTh2uzrWlVhw5rY8ttyEi36+h3cpV+REKSj+R8h+cqbBPAPMhK4VuxJcg/+dNH0+VHqxaEUp5t1UNv2mLOnLTSZbdnxEjUbIUqv9l0JosHlBeo6mLk0uI9/m76Qd85K007JmABII90rHLnJ5TTgrn+hOBXSlAnJSPtY7sURxLmJSMzWmBLmj+WQVRXdXhm65VRxNTLJ+JQowl8EKe4AK9w1RDE0UaYOPX4TVfJBqesEXEbjPAKODHX/3aZROpxTLhEsE4AoJXOyXPA0PLKSg+Vz6LtI+KrS5VzLd3ivkSeyv/VBBiSof/PR9yZCq1U6SfjKRlfFUugq5yxev11Vf4TzgiyOnCCd93ogj1QV9MyOrMMNRzsd0kzFvQQUOXwrqwCFnOlNlZkJs9CBxlN+s+ulMU5Eoa8XKdTsz2mo7wu1ApgST8F7xkWmE9wc21+KHo5MaF9MncTA5UyCs2HBuAebWSCDU3oNEpQq9IrpbdMrtaxtsjBEN3vgp/qacn4/6m9Q1gNgXPzO72UxB7ib+ghAQruDsKL0e2XLUQ6QWUtqfRCJ3BXlciTFvg=
  template:
    metadata:
      creationTimestamp: null
      name: inception-secret
      namespace: default
